ex0: ex0.go
	gccgo -ggdb3 ex0.go -o ex0
	
ex1: ex1.go
	gccgo -ggdb3 ex1.go -o ex1
	
ex2: ex2.go
	gccgo -ggdb3 ex2.go -o ex2
	
ex3: ex3.go
	gccgo -ggdb3 ex3.go -o ex3
	
all:
	make ex0
	make ex1
	make ex2
	make ex3
