ex0: ex0.cpp
	g++ -ggdb3 ex0.cpp -o ex0
	
ex1: ex1.cpp
	g++ -ggdb3 ex1.cpp -o ex1
	
ex2: ex2.cpp
	g++ -ggdb3 ex2.cpp -o ex2
	
ex3: ex3.cpp
	g++ -ggdb3 ex3.cpp -o ex3
	
all:
	make ex0
	make ex1
	make ex2
	make ex3
